header:
  - paths:
      - "**/*.go"
    license:
      spdx-id: Apache-2.0
      copyright-owner: Percona LLC
      copyright-year: 2023
# The following files are ignored because they contain code derived from Grafana,
# which is licensed under Apache 2.0 and has its own license header/notice.
ignore:
  - pkg/grafana/templating/macros.go
  - pkg/grafana/templating/variable_format.go
  - pkg/grafana/types/variable_types.go
