header:
  - paths:
      - "**/*.go"
    license:
      spdx-id: Apache-2.0
      copyright-owner: Percona LLC
      copyright-year: 2023
    paths-ignore:
      - pkg/grafana/templating/macros.go
      - pkg/grafana/templating/variable_format.go
      - pkg/grafana/types/variable_types.go
