#!/bin/bash

# This script runs go tests.

set -o errexit

timeout="6000s"
build_tag="$1"

trap exit 1 SIGINT

go clean -testcache

run_e2e_tests() {
	go test -timeout "$timeout" -tags e2e ./internal/test/e2e/... -v
}

run_unit_tests() {
	go test -timeout "$timeout" ./... -v \
		| grep -v '\[no test files\]' # Filtering lines like `? pmm-dump/pkg/victoriametrics [no test files]`
}

if [[ -n $build_tag ]]; then
	run_e2e_tests
else
	run_unit_tests
fi
